export enum PRODUCT_STATUS {
  MOI_SAN_XUAT = 1,
  DUA_VE_DAI_LY = 2,
  DA_BAN = 3,
  LOI_CAN_BAO_HANH = 4,
  DANG_SUA_CHUA_BAO_HANH = 5,
  DA_BAO_HANH_XONG = 6,
  DA_TRA_LAI_BAO_HANH_CHO_KHACH_HANG = 7,
  LOI_CAN_TRA_VE_NHA_MAY = 8,
  LOI_DA_DUA_VE_CO_SO_SAN_XUAT = 9,
  LOI_CAN_TRIEU_HOI = 10,
  HET_THOI_GIAN_BAO_HANH = 11,
  TRA_LAI_CO_SO_SAN_XUAT = 12,
}
